version: "3.9"
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=cedict
    ports:
      - 27023:27017
    volumes:
      - db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://db:27017/cedict

volumes:
  db: {}
